Updates to get Linting charts...
------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 launch-agent => (version: "0.5.0", path: "charts/launch-agent")
------------------------------------------------------------------------------------------------------------------------

"bitnami" already exists with the same configuration, skipping
Linting chart "launch-agent => (version: \"0.5.0\", path: \"charts/launch-agent\")"
Checking chart "launch-agent => (version: \"0.5.0\", path: \"charts/launch-agent\")" for a version bump...
Old chart version: 0.4.0
New chart version: 0.5.0
Chart version ok.
Validating /Users/zb/github/wandb/helm-charts/charts/launch-agent/Chart.yaml...
Validation success! 👍
Validating maintainers...

Linting chart with values file "charts/launch-agent/ci/basic-values.yaml"...

==> Linting charts/launch-agent
[ERROR] Chart.yaml: invalid icon URL 'rocket.png'

Error: 1 chart(s) linted, 1 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✖︎ launch-agent => (version: "0.5.0", path: "charts/launch-agent") > failed waiting for process: exit status 1
------------------------------------------------------------------------------------------------------------------------
failed linting charts: failed processing charts working